package com.kiwicorp.dumbdue

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.os.Build
import androidx.annotation.RequiresApi
import androidx.core.content.getSystemService
import com.jakewharton.threetenabp.AndroidThreeTen
import com.kiwicorp.dumbdue.di.DaggerAppComponent
import dagger.android.AndroidInjector
import dagger.android.support.DaggerApplication
import timber.log.Timber

class DumbDueApplication : DaggerApplication() {
    /**
     * Tell Dagger which [AndroidInjector] to use - in our case
     * [com.kiwicorp.dumbdue.di.AppComponent]. `DaggerAppComponent`
     * is a class generated by Dagger based on the `AppComponent` class.
     */
    override fun applicationInjector(): AndroidInjector<out DaggerApplication> {
        return DaggerAppComponent.factory().create(applicationContext)
    }

    override fun onCreate() {
        super.onCreate()

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            makeNotificationChannel()
        }

        Timber.plant(Timber.DebugTree())

        AndroidThreeTen.init(this)
    }

    @RequiresApi(Build.VERSION_CODES.O)
    private fun makeNotificationChannel() {

        val notificationManager: NotificationManager = getSystemService()
            ?: throw Exception("Notification Manager Not Found")

        notificationManager.createNotificationChannel(
            NotificationChannel(
                CHANNEL_ID_REMINDER,
                "Reminders",
                NotificationManager.IMPORTANCE_HIGH
            ).apply { lockscreenVisibility = Notification.VISIBILITY_PRIVATE }
        )
    }

}

const val CHANNEL_ID_REMINDER = "reminder_channel_id"